### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by dharani2206**

### CODE REVIEW

**Comment by charanTejJ** [comment]
please state the reason of access

**Comment by dharani2206** [comment]
> please state the reason of access

shut up n approvee

**Comment by charanTejJ** [comment]
:octocat:  u are talking to owner

**Comment by dharani2206** [comment]
> :octocat: u are talking to owner

soo whatt

**Comment by dharani2206** [comment]
> > :octocat: u are talking to owner
> 
> soo whatt
pp approve

**Review by charanTejJ — APPROVED** [review]

**Pull request merged**
